[Modify] Only support cipher suite C16, 17
Follow the Hyve BMC spec,
disable unsecure cipher suites.

Note:
    By the AMI design,
    The cmd result for "RMCP+ Messaging Cipher Suite Entry Support"
    is hard code, that may need to modify the common code to match the behavior.

Tested:
	~# ipmitool -H 10.19.80.111 -U admin -P admin -I lanplus -C 17  lan print 1 | grep "RMCP+ Cipher Suites"
	RMCP+ Cipher Suites     : 0,1,2,3,6,7,8,11,12,15,16,17

	~# ipmitool -H 10.19.80.111 -U admin -P admin -I lanplus lan print 1 -C 0
	Error in open session response message : no matching cipher suite

	Error: Unable to establish IPMI v2 / RMCP+ session
	~# ipmitool -H 10.19.80.111 -U admin -P admin -I lanplus lan print 1 -C 1
	Error in open session response message : no matching cipher suite

	Error: Unable to establish IPMI v2 / RMCP+ session
	~# ipmitool -H 10.19.80.111 -U admin -P admin -I lanplus lan print 1 -C 2
	Error in open session response message : no matching cipher suite

	Error: Unable to establish IPMI v2 / RMCP+ session
	:~# ipmitool -H 10.19.80.111 -U admin -P admin -I lanplus lan print 1 -C 3
	Error in open session response message : no matching cipher suite

	Error: Unable to establish IPMI v2 / RMCP+ session
	~# ipmitool -H 10.19.80.111 -U admin -P admin -I lanplus lan print 1 -C 6
	Error in open session response message : no matching cipher suite

	Error: Unable to establish IPMI v2 / RMCP+ session
	~# ipmitool -H 10.19.80.111 -U admin -P admin -I lanplus lan print 1 -C 7
	Error in open session response message : no matching cipher suite

	Error: Unable to establish IPMI v2 / RMCP+ session
	~# ipmitool -H 10.19.80.111 -U admin -P admin -I lanplus lan print 1 -C 8
	Error in open session response message : no matching cipher suite

	Error: Unable to establish IPMI v2 / RMCP+ session
	~# ipmitool -H 10.19.80.111 -U admin -P admin -I lanplus lan print 1 -C 11
	Error in open session response message : no matching cipher suite

	Error: Unable to establish IPMI v2 / RMCP+ session
	~# ipmitool -H 10.19.80.111 -U admin -P admin -I lanplus lan print 1 -C 12
	Error in open session response message : no matching cipher suite

	Error: Unable to establish IPMI v2 / RMCP+ session
	~# ipmitool -H 10.19.80.111 -U admin -P admin -I lanplus lan print 1 -C 15
	Error in open session response message : no matching cipher suite

	Error: Unable to establish IPMI v2 / RMCP+ session
	~# ipmitool -H 10.19.80.111 -U admin -P admin -I lanplus lan print 1 -C 16
	Set in Progress         : Set Complete
	Auth Type Support       :
	Auth Type Enable        : Callback :

	User Lockout Interval   : 0
	~# ipmitool -H 10.19.80.111 -U admin -P admin -I lanplus lan print 1 -C 17
	Set in Progress         : Set Complete
	Auth Type Support       :
	Auth Type Enable        : Callback :